version: "3.7"
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    env_file: .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${DB_VOLUMES}:/var/lib/mysql
      - ${DB_SQL_SCRIPTS}:/docker-entrypoint-initdb.d
  alarm-app:
    container_name: alarm-app
    build:
      context: ${ALARM_APP_ROOT}
      dockerfile: Dockerfile
    ports:
      - "8080:8001"
